#!/usr/bin/env bash
# Compte les lignes du mod ExoInstruments, par catégorie.
#
#   ./tools/count_lines.sh          résumé
#   ./tools/count_lines.sh -d       + détail fichier par fichier
#
# Exclus : obj/, bin/, env/ (venv Python), et les fichiers .cs générés
# (marqués "GENERATED by tools/...") qui sont comptés à part.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

DETAIL=0
[[ "${1:-}" == "-d" || "${1:-}" == "--detail" ]] && DETAIL=1

PRUNE=( -name obj -o -name bin -o -name env -o -name .git -o -name __pycache__ )

# find_files <ext...> -> liste de chemins sur stdout
find_files() {
  local args=()
  for ext in "$@"; do
    args+=( -o -name "*.$ext" )
  done
  find . \( "${PRUNE[@]}" \) -prune -o -type f \( "${args[@]:1}" \) -print | sort
}

is_generated() {
  head -5 "$1" | grep -qi "generated by tools/"
}

count() {  # count <liste de fichiers sur stdin> -> "nb_fichiers nb_lignes"
  local files n total
  files=$(cat)
  if [[ -z "$files" ]]; then echo "0 0"; return; fi
  n=$(printf '%s\n' "$files" | wc -l | tr -d ' ')
  total=$(printf '%s\n' "$files" | tr '\n' '\0' | xargs -0 cat | wc -l | tr -d ' ')
  echo "$n $total"
}

# %-Ns compte les octets, pas les caractères : on pad à la main pour que les
# libellés accentués restent alignés.
row() {
  # largeur affichée = octets moins les octets de continuation UTF-8 (0x80-0xBF)
  local width; width=$(printf '%s' "$1" | LC_ALL=C tr -d '\200-\277' | LC_ALL=C wc -c)
  local pad=$(( 26 - width ))
  (( pad < 1 )) && pad=1
  printf "  %s%*s %6s files %8s lines\n" "$1" "$pad" "" "$2" "$3"
}

# --- C# : sources du mod, tables générées, harnais de test (tools/) ---
handwritten=""
generated=""
tests=""
while IFS= read -r f; do
  if [[ "$f" == ./tools/* ]]; then
    tests+="$f"$'\n'
  elif is_generated "$f"; then
    generated+="$f"$'\n'
  else
    handwritten+="$f"$'\n'
  fi
done < <(find_files cs)
handwritten="${handwritten%$'\n'}"
generated="${generated%$'\n'}"
tests="${tests%$'\n'}"

read -r CS_N CS_L     <<< "$(printf '%s' "$handwritten" | count)"
read -r GEN_N GEN_L   <<< "$(printf '%s' "$generated"   | count)"
read -r TEST_N TEST_L <<< "$(printf '%s' "$tests"       | count)"
read -r PY_N PY_L   <<< "$(find_files py | count)"
read -r CFG_N CFG_L <<< "$(find_files cfg netkan | count)"
read -r DOC_N DOC_L <<< "$(find_files md | count)"

echo
echo "ExoInstruments - line count ($ROOT)"
echo
row "C# mod (hand-written)"     "$CS_N" "$CS_L"
row "C# generated tables"      "$GEN_N" "$GEN_L"
row "C# test harnesses"        "$TEST_N" "$TEST_L"
row "Python (tools/)"          "$PY_N"  "$PY_L"
row "KSP configs (.cfg)"       "$CFG_N" "$CFG_L"
row "Documentation (.md)"      "$DOC_N" "$DOC_L"
echo "  ------------------------------------------------------"
row "MOD (C# main + configs)" "$((CS_N + CFG_N))" "$((CS_L + CFG_L))"
row "TOTAL" "$((CS_N + GEN_N + TEST_N + PY_N + CFG_N + DOC_N))" \
            "$((CS_L + GEN_L + TEST_L + PY_L + CFG_L + DOC_L))"
echo

if (( DETAIL )); then
  echo "Hand-written C# breakdown (top 30):"
  printf '%s\n' "$handwritten" | tr '\n' '\0' | xargs -0 wc -l | grep -v ' total$' \
    | sort -rn | head -30
  echo
  echo "Python breakdown (top 15):"
  find_files py | tr '\n' '\0' | xargs -0 wc -l | grep -v ' total$' | sort -rn | head -15
  echo
fi
