#!/usr/bin/env python3
"""Generates Core/StarProperNameTable.cs from the IAU Catalog of Star Names.

WHY IT EXISTS. The catalogue the exoplanet instruments hunt through is the Yale Bright Star
Catalogue, whose Name column carries Bayer and Flamsteed designations: alf Lyr, 51 Peg. Nobody
types "alf Lyr". They type Vega. Without a name table the search box cannot find, by the name it is
universally known by, the brightest star it can point at.

WHICH NAMES. The IAU Catalog of Star Names (IAU-CSN), maintained by the IAU Division C Working
Group on Star Names, which is the body that decides what a star is officially called. That matters
more here than convenience: proper names are the part of astronomical nomenclature with the most
folklore attached, and half the "traditional" names in circulation are nineteenth-century
mistranscriptions. The WGSN list is the one an author can cite.

WHAT IS AND IS NOT KEPT. Names, designations, HIP and HD numbers, position and magnitude. The HD
number is the join: the Bright Star Catalogue export carries one, so a name lands on the right star
by catalogue number rather than by matching strings. Rows with neither an HD nor an HR designation
still ship (they are exoplanet hosts named by the WGSN, findable by position), but they cannot
attach to a BSC star and are not expected to.

Run:
    ./env/bin/python generate_star_names.py --out ../ExoInstruments/Core/StarProperNameTable.cs
"""

import argparse
import re
import urllib.request

# The WGSN's own working copy, maintained by the group's secretary and linked from the IAU's
# naming-stars page as the machine-readable form of the official list.
CATALOG_URL = "https://www.pas.rochester.edu/~emamajek/WGSN/IAU-CSN.txt"

# Fixed-width starts of the left-hand fields. The right-hand fields are whitespace-separated and
# parsed as tokens instead, because a negative magnitude (Sirius, -1.45) runs into the column
# before it and fixed-width slicing cuts it in half.
LEFT_FIELDS = [
    ("name_ascii", 0, 18),
    ("name_diacritics", 18, 36),
    ("designation", 36, 49),
    ("bayer_id", 49, 55),
    ("bayer_greek", 55, 61),
    ("constellation", 61, 65),
    ("component", 65, 70),
]

# The catalogue writes an absent HD number as 999999 in some rows and as an underscore in others.
HD_ABSENT = "999999"

DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
HR_DESIGNATION = re.compile(r"^HR\s+(\d+)$")
HD_DESIGNATION = re.compile(r"^HD\s+(\d+)$")


def fetch(url):
    with urllib.request.urlopen(url, timeout=120) as response:
        return response.read().decode("utf-8")


def parse(text):
    stars = []
    for line in text.splitlines():
        if not line.strip() or line[0] in "#$":
            continue

        row = {label: line[start:end].strip() for label, start, end in LEFT_FIELDS}
        tokens = line[70:].split()
        if len(tokens) < 8 or not DATE.match(tokens[7]):
            raise SystemExit(f"unreadable IAU-CSN row (right-hand fields): {line!r}")

        row["magnitude"] = tokens[1]
        row["band"] = tokens[2]
        row["hip"] = tokens[3]
        row["hd"] = tokens[4]
        row["ra_deg"] = float(tokens[5])
        row["dec_deg"] = float(tokens[6])
        stars.append(row)
    return stars


def as_int(value, absent=("_", "", HD_ABSENT)):
    return -1 if value in absent else int(value)


def as_double(value):
    return float("nan") if value in ("_", "") else float(value)


def hr_number(designation):
    match = HR_DESIGNATION.match(designation)
    return int(match.group(1)) if match else -1


def hd_from_designation(designation):
    match = HD_DESIGNATION.match(designation)
    return int(match.group(1)) if match else -1


def emit(stars, out):
    out.write("// GENERATED by tools/generate_star_names.py; do not edit by hand.\n")
    out.write("//\n")
    out.write("// The IAU Catalog of Star Names (IAU-CSN), the official proper names approved by the\n")
    out.write("// IAU Division C Working Group on Star Names. The Bright Star Catalogue this mod hunts\n")
    out.write("// through carries Bayer and Flamsteed designations only, so without this table the\n")
    out.write("// search box cannot find Vega by typing Vega.\n")
    out.write("//\n")
    out.write("// Arrays run parallel. -1 means the catalogue carries no such number for that star;\n")
    out.write("// NaN means no magnitude. Positions are J2000 degrees.\n")
    out.write("\n")
    out.write("namespace ExoInstruments.Core\n{\n")
    out.write("    internal static class StarProperNameTable\n    {\n")
    out.write(f"        public const int Count = {len(stars)};\n\n")

    write_strings(out, "Names", "IAU-approved proper name, ASCII form.",
                  [s["name_ascii"] for s in stars])
    write_strings(out, "NamesWithDiacritics", "The same name as the IAU writes it, accents and all.",
                  [s["name_diacritics"] for s in stars])
    write_strings(out, "Designations", "The designation the WGSN attached the name to, e.g. \"HR 7001\".",
                  [s["designation"] for s in stars])
    write_strings(out, "BayerIds", "Bayer or Flamsteed identifier within the constellation, e.g. \"alf\", \"tet01\".",
                  [s["bayer_id"] if s["bayer_id"] != "_" else "" for s in stars])
    write_strings(out, "Constellations", "Three-letter IAU constellation abbreviation.",
                  [s["constellation"] for s in stars])
    write_strings(out, "Components", "Which component of a multiple system the name belongs to, or empty.",
                  [s["component"] if s["component"] != "_" else "" for s in stars])

    write_ints(out, "HipNumbers", "Hipparcos number, -1 when the catalogue has none.",
               [as_int(s["hip"]) for s in stars])
    write_ints(out, "HdNumbers",
               "Henry Draper number, -1 when absent. This is the join against the Bright Star Catalogue.",
               [max(as_int(s["hd"]), hd_from_designation(s["designation"])) for s in stars])
    write_ints(out, "HrNumbers",
               "Bright Star Catalogue number, read off the designation, -1 when the name is not attached to one.",
               [hr_number(s["designation"]) for s in stars])

    write_doubles(out, "RaDeg", "Right ascension, J2000 degrees.", [s["ra_deg"] for s in stars])
    write_doubles(out, "DecDeg", "Declination, J2000 degrees.", [s["dec_deg"] for s in stars])
    write_doubles(out, "Magnitudes", "Apparent magnitude in the band named alongside, NaN when absent.",
                  [as_double(s["magnitude"]) for s in stars])
    write_strings(out, "MagnitudeBands", "Photometric band the magnitude is in.",
                  [s["band"] if s["band"] != "_" else "" for s in stars], last=True)

    out.write("    }\n}\n")


def write_strings(out, name, doc, values, last=False):
    out.write(f"        /// <summary>{doc}</summary>\n")
    out.write(f"        public static readonly string[] {name} =\n        {{\n")
    for i in range(0, len(values), 6):
        row = ", ".join('"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"' for v in values[i:i + 6])
        out.write(f"            {row},\n")
    out.write("        };\n" + ("" if last else "\n"))


def write_ints(out, name, doc, values):
    out.write(f"        /// <summary>{doc}</summary>\n")
    out.write(f"        public static readonly int[] {name} =\n        {{\n")
    for i in range(0, len(values), 12):
        out.write("            " + ", ".join(str(v) for v in values[i:i + 12]) + ",\n")
    out.write("        };\n\n")


def write_doubles(out, name, doc, values):
    out.write(f"        /// <summary>{doc}</summary>\n")
    out.write(f"        public static readonly double[] {name} =\n        {{\n")
    for i in range(0, len(values), 6):
        row = ", ".join("double.NaN" if v != v else repr(v) for v in values[i:i + 6])
        out.write(f"            {row},\n")
    out.write("        };\n\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="path to write StarProperNameTable.cs to")
    parser.add_argument("--input", help="local copy of IAU-CSN.txt instead of downloading")
    args = parser.parse_args()

    text = open(args.input, encoding="utf-8").read() if args.input else fetch(CATALOG_URL)
    stars = parse(text)

    # The list has been over 300 names since 2016 and only grows; anything much smaller means a
    # truncated download or a changed format rather than a shorter catalogue.
    if len(stars) < 300:
        raise SystemExit(f"only {len(stars)} names parsed, expected the IAU-CSN's several hundred")

    duplicates = sorted({n for n in (s["name_ascii"] for s in stars)
                         if [t["name_ascii"] for t in stars].count(n) > 1})
    if duplicates:
        raise SystemExit(f"the same proper name appears twice: {duplicates}")

    with_hd = sum(1 for s in stars if as_int(s["hd"]) > 0 or hd_from_designation(s["designation"]) > 0)
    with open(args.out, "w", encoding="utf-8") as handle:
        emit(stars, handle)
    print(f"wrote {args.out}: {len(stars)} IAU proper names, {with_hd} with an HD number")


if __name__ == "__main__":
    main()
