#!/usr/bin/env python3
"""Generates Core/CieColourMatchingTable.cs from the official CIE tables.

WHY GENERATED. The CIE 1931 2-degree standard observer is 471 rows of three numbers and the sRGB
matrix is nine more. Typing them from memory or from a web page is exactly the kind of transcription
that produces a plausible but wrong colour for every object in the mod, and no test on the rest of
the pipeline would notice. So they are emitted from colour-science, which ships the CIE's own
tabulation, and tools/colour-tests compares the emitted file back against it.

The alternative -- the multi-lobe Gaussian fit of Wyman, Sloan & Shirley (2013, JCGT 2, 1) -- is an
approximation to these curves with a stated error of about 1% of peak. That is small, but it is an
approximation where an exact table costs nothing but source lines.

Run:
    ./env/bin/pip install colour-science
    ./env/bin/python generate_cie_table.py > ../ExoInstruments/Core/CieColourMatchingTable.cs
"""

import sys

import numpy as np
import colour


def main():
    cmfs = colour.MSDS_CMFS["CIE 1931 2 Degree Standard Observer"]
    wavelengths = np.arange(360, 831, 1)
    values = np.array([cmfs[w] for w in wavelengths])

    # The sRGB colourspace's own XYZ -> RGB matrix, at full precision rather than the rounded
    # four-figure form usually quoted. Derived by colour-science from the IEC 61966-2-1 primaries
    # and the D65 white point.
    space = colour.models.RGB_COLOURSPACE_sRGB
    # Derived from the primaries and the white point, which is how IEC 61966-2-1 DEFINES the
    # transform; the four-decimal matrix usually quoted is a rounding of this. The harness checks
    # that the two agree to that rounding.
    npm = colour.normalised_primary_matrix(space.primaries, space.whitepoint)
    m = np.linalg.inv(npm)
    white = space.whitepoint

    out = sys.stdout.write
    out("// GENERATED by tools/generate_cie_table.py -- do not edit by hand.\n")
    out("//\n")
    out("// CIE 1931 2-degree standard observer colour matching functions, 360-830 nm at 1 nm,\n")
    out("// and the sRGB (IEC 61966-2-1) XYZ-to-linear-RGB matrix with its D65 white point.\n")
    out("// Emitted from colour-science " + colour.__version__ + ", which ships the CIE's own\n")
    out("// tabulation; tools/colour-tests compares this file back against it.\n")
    out("\n")
    out("namespace ExoInstruments.Core\n{\n")
    out("    internal static class CieColourMatchingTable\n    {\n")
    out(f"        public const double MinWavelengthNm = {wavelengths[0]}.0;\n")
    out(f"        public const double MaxWavelengthNm = {wavelengths[-1]}.0;\n")
    out("        public const double StepNm = 1.0;\n\n")

    out("        /// <summary>x-bar, the long-wavelength-weighted response, one entry per nanometre.</summary>\n")
    out("        public static readonly double[] XBar =\n        {\n")
    write_rows(out, values[:, 0])
    out("        };\n\n")

    out("        /// <summary>y-bar, which is also the CIE luminous efficiency function V(lambda) by construction.</summary>\n")
    out("        public static readonly double[] YBar =\n        {\n")
    write_rows(out, values[:, 1])
    out("        };\n\n")

    out("        /// <summary>z-bar, the short-wavelength response.</summary>\n")
    out("        public static readonly double[] ZBar =\n        {\n")
    write_rows(out, values[:, 2])
    out("        };\n\n")

    out("        /// <summary>XYZ to linear sRGB, IEC 61966-2-1, D65.</summary>\n")
    out("        public static readonly double[,] XyzToLinearSrgb =\n        {\n")
    for row in m:
        out("            { " + ", ".join(f"{v:.17g}" for v in row) + " },\n")
    out("        };\n\n")

    out("        /// <summary>D65 chromaticity, the white point sRGB is defined against.</summary>\n")
    out(f"        public const double D65x = {white[0]:.17g};\n")
    out(f"        public const double D65y = {white[1]:.17g};\n")
    out("    }\n}\n")
    return 0


def write_rows(out, column, per_line=8):
    for i in range(0, len(column), per_line):
        chunk = column[i:i + per_line]
        out("            " + ", ".join(f"{v:.10g}" for v in chunk) + ",\n")


if __name__ == "__main__":
    sys.exit(main())
