#!/usr/bin/env python3
"""Generates Core/AirglowTable.cs from ESO's own sky model.

WHY THIS EXISTS. The night sky is not a continuum. It carries strong, narrow emission lines -- the
[O I] green line at 557.7 nm, the [O I] red doublet at 630.0 and 636.4, the sodium D lines, and from
650 nm upward a dense forest of OH Meinel bands -- and a narrowband filter either sits on one of them
or it does not. That is the difference between an [O I] 6300 frame from the ground being hopeless and
being merely difficult, and a sky modelled as a smooth continuum cannot express it at all.

WHERE THE NUMBERS COME FROM. ESO's SkyCalc sky model (Noll et al. 2012, A&A 543, A92; Jones et al.
2013, A&A 560, A91), queried through its own public service. Its airglow component is built on the
flux-calibrated Paranal sky spectra of Hanuschik (2003, A&A 407, 1157) and Patat (2008, A&A 481, 575),
so this is a published, calibrated model rather than a set of line strengths taken from a table by
hand.

WHAT IS STORED. The airglow spectral density, in rayleighs per nanometre, BIN-INTEGRATED from the
model's 0.02 nm grid onto a 0.1 nm one. Bin integration rather than sampling, because what a filter
collects is the integral over its passband: resampling would move flux, while binning preserves it
exactly in every window. Lines and continuum are stored separately, since they scale with airmass
differently -- see Core/Airglow.

Run:
    ./env/bin/pip install skycalc_cli astropy numpy
    ./env/bin/python generate_airglow_table.py --out ../ExoInstruments/Core/AirglowTable.cs

The output goes to a FILE, never to stdout: the skycalc client prints an informational note on
stdout when it runs, and a generated source file assembled by shell redirection silently swallowed
it as its first line -- a syntax error at best, and at worst a corruption nothing would notice.
"""

import argparse
import io
import sys

import numpy as np


STEP_NM = 0.1
MIN_NM = 350.0
MAX_NM = 1000.0
QUERY_STEP_NM = 0.02

# ph/s/m2/arcsec2 to rayleighs: 1 R is 1e6/(4 pi) photons per cm2 per s per steradian, and one square
# arcsecond is 2.35044e-11 sr.
PHOTON_UNIT_TO_RAYLEIGH = (1e-4 / 2.35044e-11) / (1e6 / (4 * np.pi))

# Solar radio flux at 10.7 cm, in solar flux units. The airglow's brightest lines track the solar
# cycle strongly -- the [O I] red line varies by a factor of several -- so a value has to be chosen
# and stated. 130 is mid-cycle; SkyCalc's own default range is 0 to 300.
SOLAR_FLUX = 130.0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    from skycalc_cli.skycalc import SkyModel
    from astropy.io import fits

    model = SkyModel()
    model.callwith({
        "airmass": 1.0, "wmin": MIN_NM, "wmax": MAX_NM, "wdelta": QUERY_STEP_NM,
        "observatory": "paranal", "vacair": "air", "msolflux": SOLAR_FLUX,
        "incl_moon": "N", "incl_zodiacal": "N", "incl_starlight": "N", "incl_therm": "N",
        "incl_loweratm": "Y", "incl_upperatm": "Y", "incl_airglow": "Y",
    })
    model.write("/tmp/airglow_query.fits")
    with fits.open("/tmp/airglow_query.fits") as hdul:
        data = hdul[1].data

    lam = np.asarray(data["lam"], dtype=float)
    lines = np.asarray(data["flux_ael"], dtype=float) * PHOTON_UNIT_TO_RAYLEIGH * 1e-3
    cont = np.asarray(data["flux_arc"], dtype=float) * PHOTON_UNIT_TO_RAYLEIGH * 1e-3

    edges = np.arange(MIN_NM, MAX_NM + 0.5 * STEP_NM, STEP_NM)
    binned_lines = bin_integrate(lam, lines, edges)
    binned_cont = bin_integrate(lam, cont, edges)

    total_lines = float(np.sum(binned_lines) * STEP_NM)
    total_cont = float(np.sum(binned_cont) * STEP_NM)

    buffer = io.StringIO()
    out = buffer.write
    out("// GENERATED by tools/generate_airglow_table.py -- do not edit by hand.\n")
    out("//\n")
    out("// Airglow spectral density at the zenith from Paranal, rayleighs per nanometre, from ESO's\n")
    out("// SkyCalc sky model (Noll et al. 2012, A&A 543, A92; Jones et al. 2013, A&A 560, A91),\n")
    out(f"// whose airglow component rests on the flux-calibrated Paranal spectra of Hanuschik (2003)\n")
    out(f"// and Patat (2008). Solar radio flux {SOLAR_FLUX:.0f} sfu, mid-cycle.\n")
    out("//\n")
    out(f"// Bin-integrated from the model's {QUERY_STEP_NM} nm grid onto {STEP_NM} nm, so the\n")
    out("// integral over any window is preserved exactly rather than resampled.\n")
    out(f"// Totals over {MIN_NM:.0f}-{MAX_NM:.0f} nm: emission lines {total_lines:.0f} R,\n")
    out(f"// residual continuum {total_cont:.0f} R.\n")
    out("\n")
    out("namespace ExoInstruments.Core\n{\n")
    out("    internal static class AirglowTable\n    {\n")
    out(f"        public const double MinWavelengthNm = {MIN_NM};\n")
    out(f"        public const double MaxWavelengthNm = {MAX_NM};\n")
    out(f"        public const double StepNm = {STEP_NM};\n")
    out(f"        public const double SolarRadioFluxSfu = {SOLAR_FLUX};\n")
    out(f"        public const double TotalLineRayleighs = {total_lines:.6g};\n")
    out(f"        public const double TotalContinuumRayleighs = {total_cont:.6g};\n\n")

    out("        /// <summary>Emission lines: the [O I] doublets, sodium, and the OH Meinel forest. Rayleighs per nanometre.</summary>\n")
    out("        public static readonly float[] LineDensity =\n        {\n")
    write_rows(out, binned_lines)
    out("        };\n\n")
    out("        /// <summary>Airglow residual continuum, rayleighs per nanometre. Smooth, and scaled by a different airmass law.</summary>\n")
    out("        public static readonly float[] ContinuumDensity =\n        {\n")
    write_rows(out, binned_cont)
    out("        };\n")
    out("    }\n}\n")
    with open(args.out, "w") as f:
        f.write(buffer.getvalue())
    print(f"wrote {args.out}")
    return 0


def bin_integrate(lam, density, edges):
    """Integral of the density over each bin, divided by the bin width: an average that preserves the
    integral. A plain interpolation would move flux between bins and lose narrow lines entirely."""
    cumulative = np.concatenate(([0.0], np.cumsum(np.diff(lam) * 0.5 * (density[1:] + density[:-1]))))
    at_edges = np.interp(edges, lam, cumulative)
    return np.diff(at_edges) / np.diff(edges)


def write_rows(out, column, per_line=8):
    for i in range(0, len(column), per_line):
        chunk = column[i:i + per_line]
        out("            " + ", ".join(f"{v:.6g}f" for v in chunk) + ",\n")


if __name__ == "__main__":
    sys.exit(main())
